ALTER TABLE public.monthly_bills
ADD COLUMN IF NOT EXISTS claimed_total_km NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS vehicle_rent_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS advance_amount NUMERIC DEFAULT 0;
